# This workflow executes the main Python script
name: Execute Script

on:
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  execute-script:
    name: Execute Script
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL}}
      FACTS_API_KEY: ${{ secrets.FACTS_API_KEY}}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install Python Dependencies
        run: pip install -r requirements.txt
        shell: bash
      - name: Run Python Script
        run: python main.py
        shell: bash
