# This workflow runs the process and posts
name: Execute Script

on:
  schedule:
    - cron: "0 12,24 * * *"

jobs:
  execute-script:
    name: Execute Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install Python Dependencies
        run: pip install -r requirements.txt
        shell: bash
      - name: Run Python Script
        run: python main.py
        shell: bash
